# Generated by Django 4.2.5 on 2023-10-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_product_countinstocks_product_countinstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='potalCode',
            new_name='postalCode',
        ),
    ]
