# Generated by Django 4.2.5 on 2023-10-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_potalcode_shippingaddress_postalcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
