# Generated by Django 4.2.5 on 2023-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholderImage.png', null=True, upload_to=''),
        ),
    ]
